# Generated by Django 5.2.9 on 2026-03-29 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0003_querylog_call_type_querylog_error_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querylog",
            name="call_type",
            field=models.CharField(
                choices=[
                    ("qa", "Question Answering"),
                    ("summary", "Summarization"),
                    ("suggestion", "Question Suggestion"),
                    ("citation", "Citation"),
                ],
                default="qa",
                help_text="Type of LLM call",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="querylog",
            name="llm_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gemini", "Google Gemini"),
                    ("openrouter", "OpenRouter"),
                    ("local_llm", "Local LLM"),
                ],
                default="",
                help_text="LLM provider: gemini / openrouter / local_llm",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="querylog",
            name="llm_status",
            field=models.CharField(
                choices=[("success", "Success"), ("error", "Error")],
                default="success",
                help_text="Call status: success / error",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notebook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="django_app.notebook",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("sources", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="django_app.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
